### ISSUE TITLE
AttributeError: 'function' object has no attribute 'filter'

### ISSUE THREAD

**Issue by bmdetera** [scikit-mobility/scikit-mobility#202]
`from skmob.preprocessing import filtering`

```
AttributeError                            Traceback (most recent call last)
<ipython-input-81-84776338ffda> in <module>
      1 # assume walking/micromobility speed maximum at 10km per hour
----> 2 ftdf1 = filtering.filter(tdf1, max_speed_kmh=10.0)
      3 ftdf2 = filtering.filter(tdf2, max_speed_kmh=10.0)
      4 ftdf3 = filtering.filter(tdf3, max_speed_kmh=10.0)
      5 

AttributeError: 'function' object has no attribute 'filter'
```

**Comment by gbarlacchi** [comment]
Could you provide an example of the content of tdf1?

**Comment by bmdetera** [comment]
`<html>
<body>


7 | 1831 | 1s2d3f4g4y5u8 | 38.718178 | 141.709118 | 1568987596 | 1000 | toppage | 20210920 | 2019-09-20 13:53:16
-- | -- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>`

**Comment by jonpappalord** [comment]
Hi @bmdetera, could you please tell us which version of scikit-mobility are you using? Do you still find the same error on other TrajDataFrames?

**Comment by bmdetera** [comment]
Hi @jonpappalord it's version 1.2.2

**Comment by bmdetera** [comment]
Unfortunately I still get the same error

**Comment by michelegirolami** [comment]
Hi @bmdetera  I' working on this issue, but with version 1.2.3 (just released) the problem you mention is not reproducible. Could you provide me some more info:
- a csv with few lines (10 -20) containing the spatial data you are using. The example you reported might be not enough
- few lines of code triggering the error. For example: how you read the csv file, how you confer to a trajdataframe etc.

thanks
