### ISSUE TITLE
detection.stops not working with scikit-mobility 1.2.2: AttributeError: 'TrajDataFrame' object has no attribute '_crs'

### ISSUE THREAD

**Issue by Fr4nz83** [scikit-mobility/scikit-mobility#204]
Hi guys, apparently detection.stops doesn't work in the latest version available in conda-forge -- it returns the error message shown in the title. 

You can easily reproduce the issue by trying out the very same [example](https://scikit-mobility.github.io/scikit-mobility/reference/preprocessing.html#skmob.preprocessing.detection.stops) you provided in the documentation.

**Comment by jonpappalord** [comment]
Hi @Fr4nz83, is the error you get the following one?

`AttributeError: 'TrajDataFrame' object has no attribute '_crs'`

**Comment by Fr4nz83** [comment]
> Hi @Fr4nz83, is the error you get the following one?
> 
> `AttributeError: 'TrajDataFrame' object has no attribute '_crs'`

Dear Luca, yes it is.

**Comment by GiulianoCornacchia** [comment]
Hi @Fr4nz83 in order to solve this issue is necessary to downgrade `pandas` at the version 1.2.5.

If you are running a jupyter notebook you need to execute the following line of code.

```!pip install pandas==1.2.5```

**Comment by Fr4nz83** [comment]
Hi @GiulianoCornacchia, I see, thank you for the temporary fix.

**Comment by abombz** [comment]
I still get that error after running !pip install pandas==1.2.5. Any other options?

**Comment by jonpappalord** [comment]
issue solved in scikit-mobility version 1.2.3 (when installing with pip in venv).
